---
general:
  cluster_capacity_dir: {{ cluster_capacity_dir }}
  results_dir: {{ results_dir }}
  log_file: "{{ log_file | default('build.log') }}"
kubernetes:
  kubeconfig: {{ kubeconfig }}
tests:
  unit_tests:
    enabled: true
  integration_tests:
    enabled: true
results_uploader:
  enabled: {{ enabled_results_uploader | default('false') }}
  target: gsbucket
  boto_config_file: {{ gsutil_config | default('/etc/boto_config') }}
  target_url: gs://cluster-capacity/pr-logs/pull/{{ issue_id }}/cluster-capacity-pull-build-redhat-tests/{{ build_id }}
  internal_target_url: https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/{{ issue_id }}/cluster-capacity-pull-build-redhat-tests/{{ build_id }}
results_notifier:
  enabled: {{ enabled_results_notifier | default('false') }}
  target: github
  project: kubernetes-incubator/cluster-capacity
  token: {{ ghtoken }}
  issue: {{ issue_id }}
  sha: {{ issue_commit }}
  context: bunny
  trigger_phrase: "be nice and run"
  target_url: https://console.cloud.google.com/storage/browser/cluster-capacity/pr-logs/pull/{{ issue_id }}/cluster-capacity-pull-build-redhat-tests/{{ build_id }}
  internal_target_url: https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/{{ issue_id }}/cluster-capacity-pull-build-redhat-tests/{{ build_id }}
  pr_comment:
    enabled: true
    error_msg: Cluster capacity build/test **errored** for commit {{ issue_commit }}
    failure_msg: Cluster capacity build/test **failed** for commit {{ issue_commit }}
    success_msg: Cluster capacity build/test **passed** for commit {{ issue_commit }}
  pr_status:
    enabled: false
    error_msg: Cluster capacity build/test **errored** for commit {{ issue_commit }}
    failure_msg: Cluster capacity build/test **failed** for commit {{ issue_commit }}
    success_msg: Cluster capacity build/test **passed** for commit {{ issue_commit }}
