---
general:
  cluster_capacity_dir: /home/jchaloup/Projects/src/github.com/kubernetes-incubator/cluster-capacity
  results_dir: /home/jchaloup/Projects/uniuni/artifacts
  log_file: "build.log"
kubernetes:
  kube_master_api: {{ apiserver_url }}
  kube_master_api_port: {{ apiserver_port }}
  kubeconfig: {{ kubeconfig }}
tests:
  unit_tests:
    enabled: true
  integration_tests:
    enabled: true
results_uploader:
  enabled: true
  target: gsbucket
  boto_config_file: /etc/boto_config
  target_url: gs://cluster-capacity/pr-logs/pull/{{ issue_id }}/cluster-capacity-pull-build-redhat-tests/{{ build_id }}
  internal_target_url: https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/{{ issue_id }}/cluster-capacity-pull-build-redhat-tests/{{ build_id }}
results_notifier:
  enabled: true
  target: github
  project: kubernetes-incubator/cluster-capacity
  token: /home/jchaloup/Projects/kubernetes-ci/ghtoken.json
  issue: {{ issue_id }}
  sha: {{ issue_commit }}
  context: bunny
  trigger_phrase: "be nice and run"
  target_url: https://console.cloud.google.com/storage/browser/cluster-capacity/pr-logs/pull/{{ issue_id }}/cluster-capacity-pull-build-redhat-tests/{{ build_id }}
  internal_target_url: https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/{{ issue_id }}/cluster-capacity-pull-build-redhat-tests/{{ build_id }}
  pr_comment:
    enabled: true
    error_msg: Cluster capacity build/test **errored** for commit {{ issue_commit }}
    failure_msg: Cluster capacity build/test **failed** for commit {{ issue_commit }}
    success_msg: Cluster capacity build/test **passed** for commit {{ issue_commit }}
  pr_status:
    enabled: false
    error_msg: Cluster capacity build/test **errored** for commit {{ issue_commit }}
    failure_msg: Cluster capacity build/test **failed** for commit {{ issue_commit }}
    success_msg: Cluster capacity build/test **passed** for commit {{ issue_commit }}
