---
general:
  ansible_dir: {{ ansible_dir }}
  results_dir: {{ results_dir }}
  log_file: "{{ log_file | default('build.log') }}"
  kubeconfig_dest_dir: {{ kubeconfig }}
deployment:
  vagrant:
    # Vagrantfile based deployment
    # Cluster consists of Vagrantboxes provisioned on a localhost
    enabled: false
    # fedora, not Fedora
    os_image: fedora
    num_nodes: 2
    ansible:
      kube_source_type: github-release
      kube_master_api_port: 6443
      kube_version: 1.4.8
  openstack:
    # OpenStack based deployment
    # Cluster consists of VMs with the same private key
    enabled: true
    # Only resource file with resources in a pre-defined form is needed
    resources: {{ resources }}
    private_key: {{ private_key | default("") }}
    os: rhel
    ansible:
      open_cadvisor_port: true
      flannel_subnet: 10.253.0.0
      flannel_prefix: 16
      source_type: localBuild
      kube_master_api_port: 6443
      kube_cert_ip: _use_aws_external_ip_
      localBuildOutput: ../../../kubernetes/_output/local/go/bin
      kube_api_address: 0.0.0.0
      docker_source: brew:latest
      fedora_bootstrap: false
results_uploader:
  enabled: {{ enabled_results_uploader | default('false') }}
  target: gsbucket
  boto_config_file: {{ gsutil_config | default('/etc/boto_config') }}
  target_url: gs://kubernetes-contrib-github-redhat/pr-logs/pull/{{ issue_id }}/kubernetes-pull-build-redhat-tests/{{ build_id }}
  internal_target_url: https://console.cloud.google.com/m/cloudstorage/b/kubernetes-contrib-github-redhat/o/pr-logs/pull/{{ issue_id }}/kubernetes-pull-build-redhat-tests/{{ build_id }}/
results_notifier:
  enabled: {{ enabled_results_notifier | default('false') }}
  target: github
  project: kubernetes/contrib
  token: /home/jchaloup/Projects/kubernetes-ci/ghtoken.json
  issue: {{ issue_id }}
  sha: {{ issue_commit }}
  context: bunny
  trigger_phrase: "be nice and run"
  target_url: https://console.cloud.google.com/storage/browser/kubernetes-contrib-github-redhat/pr-logs/pull/{{ issue_id }}/kubernetes-pull-build-redhat-tests/{{ build_id }}
  internal_target_url: https://console.cloud.google.com/m/cloudstorage/b/kubernetes-contrib-github-redhat/o/pr-logs/pull/{{ issue_id }}/kubernetes-pull-build-redhat-tests/{{ build_id }}/
  pr_comment:
    enabled: true
    error_msg: Cluster capacity build/test **errored** for commit {{ issue_commit }}
    failure_msg: Cluster capacity build/test **failed** for commit {{ issue_commit }}
    success_msg: Cluster capacity build/test **passed** for commit {{ issue_commit }}
  pr_status:
    enabled: false
    error_msg: Cluster capacity build/test **errored** for commit {{ issue_commit }}
    failure_msg: Cluster capacity build/test **failed** for commit {{ issue_commit }}
    success_msg: Cluster capacity build/test **passed** for commit {{ issue_commit }}
